### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by JulienPalard** [felipap/toml-python#6]
I'm trying to parse some toml using toml-python but I'm using Python 3.7.2 and I'm getting:

```>>> import tomlpython
>>> tomlpython.parse("foo=['''foo\nbar''']")
Traceback (most recent call last):
  File "/home/mdk/.venvs/mypay-api/lib/python3.7/site-packages/tomlpython/reader.py", line 60, in __init__
    input.read(4)
AttributeError: 'str' object has no attribute 'read'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mdk/.venvs/mypay-api/lib/python3.7/site-packages/tomlpython/parser.py", line 133, in parse
    reader = Reader(input)
  File "/home/mdk/.venvs/mypay-api/lib/python3.7/site-packages/tomlpython/reader.py", line 67, in __init__
    self.lineFeeder = StringIO(unicode(input))
NameError: name 'unicode' is not defined
```

**Comment by felipap** [comment]
Hi, Julien. I haven't touched on this code since 2013, so I'm not surprised it's throwing errors. Feel free to submit a pull request if you get around to fixing it yourself. :)
